services:
  - type: web
    name: recipe-site
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn recipe_site.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: recipe_site.settings
      - key: SECRET_KEY
        value: django-insecure-io@-qc^96evfnb^runnrpzjer-0lv+*ae2jmw+^!*-1=ipn&%6
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-db
          property: connectionString

databases:
  - name: recipe-db
    databaseName: recipe_db
    user: recipe_user
